Migration dialog balloon
tvardero/pirate-gamejam-15 pull request #75
Opened 2024-08-07 18:39 UTC by dsabella84

Update to DialogBalloon, Portrait, DialogCharVars, and PortraitSprite

2024-08-07 20:03 UTC, tvardero requested changes

2024-08-07 20:03 UTC, tvardero commented on resources/dialog_char_vars/Police officer.tres
> +[gd_resource type="Resource" script_class="DialogCharVars" load_steps=3 format=3 uid="uid://cy5h8qy1dfktv"]
whitespaces in filename is a bad omen, can you rename it to PoliceOfficer?

2024-08-07 20:03 UTC, tvardero commented on scenes/ui/DialogBalloon.cs
>      [Export] private Control balloon;
Should everything here be export, including private properties?

2024-08-07 20:03 UTC, tvardero commented on scenes/ui/DialogBalloon.cs
> +    Array<Variant> temporaryGameStates = new Array<Variant>();
Usage of godot collections is not recommended, use System.Collections instead.

2024-08-07 20:03 UTC, tvardero commented on scenes/ui/DialogBalloon.cs
> +    #region signals
`#region`s are not needed here, file is not that large

2024-08-07 20:03 UTC, tvardero commented on scenes/ui/DialogBalloon.cs
> +    private async void UpdateDialogue()
Do not use `async void`.
Everything async should return a `Task` or `Task<T>`

2024-08-07 20:03 UTC, tvardero commented on scenes/ui/DialogBalloon.cs
> +    private async void UpdateDialogue()
Reason is following: you can not await `async void` methods. This gives the caller no information of method execution status, and if it was a failure - exception will never be caught.

2024-08-07 20:03 UTC, tvardero commented on scenes/ui/DialogBalloon.cs
> +    private async void UpdateDialogue()
`async void` are allowed in one and one only scenario: subscription to ui component events, like `onButtonPress`

But even there I try to not make the method async, but call `async Task` method inside it and discard returned task:
```csharp
private void OnButtonClick() {
  _ = ExecuteSomethingAsync();
}

private async Task ExecuteSomethingAsync() {
  // something here
}
```

2024-08-07 20:04 UTC, tvardero commented on resources/dialog_char_vars/Police officer.tres
> +[gd_resource type="Resource" script_class="DialogCharVars" load_steps=3 format=3 uid="uid://cy5h8qy1dfktv"]
Reason is that when you try to specify path to this file somewhere, like in CLI, space will be argument separator, which ruins some command.
Some CLI tools do not support surrounding file path in quotes `"`

2024-08-07 20:05 UTC, tvardero commented on scenes/ui/DialogBalloon.cs
> +    Array<Variant> temporaryGameStates = new Array<Variant>();
I have a bad time working with godot collections, sometime they lose their static typing and you end up with dynamic collection. 
C# is strongly typed language and should remain so.

2024-08-07 20:15 UTC, dsabella84 commented on scenes/ui/DialogBalloon.cs
>      [Export] private Control balloon;
adding them so that they can be assigned from the editor. and this way are not used by other classes that shouldnt.

2024-08-07 20:17 UTC, dsabella84 commented on scenes/ui/DialogBalloon.cs
> +    #region signals
regions help organize the code through the editor, more of a preference item

2024-08-07 20:21 UTC, dsabella84 commented on scenes/ui/DialogBalloon.cs
> +    Array<Variant> temporaryGameStates = new Array<Variant>();
Thats part of the Dialogue addon, thats used in its calls

2024-08-07 20:26 UTC, dsabella84 commented on scenes/ui/DialogBalloon.cs
> +    private async void UpdateDialogue()
Thanks for the advice ill add it in.

2024-08-08 07:14 UTC, tvardero requested changes

2024-08-08 07:14 UTC, tvardero commented on scenes/dialogue/portraits/PortraitSprite.gd
> -class_name PortraitSprite
I see file gdscript file deleted, but i dont see C# script for it.

2024-08-08 07:14 UTC, tvardero commented on scenes/ui/DialogBalloon.cs
>      [Export] private AudioStream default_talk_sound;
C# has PascalCase naming convention. Everything, except fields use UpperPascalCase, and field use lowerPascalCase.
Private fields (and fields only) should start with underscore: `private bool _myHiddenData;`

2024-08-08 07:14 UTC, tvardero commented on scenes/ui/DialogBalloon.cs
> +      {
Too complex for setter, move to method.

2024-08-08 07:14 UTC, tvardero commented on scenes/ui/DialogBalloon.cs
> +        DialogueManager.Mutated -= OnMutated;
Won't work, as each time you reference method by its name - a new delegate instance is created.

Correct way is as follows:
```csharp
private void DoSomething() {
Action<string> myStringHandler = HandleStringMethod;
eventProducer.OnStringEvent += myStringHandler;
// ...
eventProducer.OnStringEvent -= myStringHandler;
}

private void HandleStringMethod(string argument) {
// ...
}
```

2024-08-08 07:14 UTC, tvardero commented on scenes/ui/DialogBalloon.cs
>      [Export] private Control balloon;
Make them public properties then.
Private fields (actually any fields, with any access modifiers) should remain to the class only and not be modified from external.

Reason is that when you will need - you won't be able to catch field data change inbetween, when some external place mutates it - you dont have a setter to place breakpoint onto.

2024-08-08 10:14 UTC, dsabella84 commented on scenes/dialogue/portraits/PortraitSprite.gd
> -class_name PortraitSprite
Its right here: scenes/dialogue/portraits/PortraitSprite.cs

2024-08-09 22:57 UTC, tvardero approved these changes

2024-08-09 22:58 UTC, merged